### ISSUE TITLE
Upgrade Closure Compiler

### ISSUE THREAD

**Issue by twwwt** [eriwen/gradle-js-plugin#116]
As far as I can see, version 1.12.1 of the plugin uses a rather outdated version of Google's Closure Compiler v20131014. Would it be possible to make a 1.12.2 release that upgrades to the latest version v20150315. This might also resolve issue #109.

Thanks

**Comment by kylecordes** [comment]
This would be very helpful here also. The JavaScript development world is moving along quite quickly, with no commits in this project since November I suspect its maintainers have moved on. That is a shame, there is a considerable elegance to a Gradle plug-in for this purpose, Which is somewhat lost with the more brutal approach of shelling out to node or whatever to run a different JavaScript tooling stack.
